name: OpenAPI

on:
  push:
    branches: ["**"]
    paths:
      - 'doc/api/**'
      - '.github/workflows/openapi.yml'
  pull_request:
    paths:
      - 'doc/api/**'
      - '.github/workflows/openapi.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  openapi:
    uses: veraison/ci/.github/workflows/openapi.yml@main
    with:
      specs: 'doc/api/keys/keys.yaml'
